exclude: "^src/chatapp_api/alembic/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: end-of-file-fixer


  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.2
    hooks:
    -   id: auto-walrus

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10
        files: ^src/|tests/

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: ^src/|tests/

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        files: ^src/|tests/
        additional_dependencies: [flake8-isort]
        args: ["--config=.flake8"]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
