"""chat, friendship

Revision ID: de133ebf6c6d
Revises: 3e3f56271e4e
Create Date: 2022-09-23 12:12:20.624965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de133ebf6c6d'
down_revision = '3e3f56271e4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friendship_id'), 'friendship', ['id'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_id'), 'membership', ['id'], unique=False)
    op.drop_table('user_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chat',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name='user_chat_chat_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_chat_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id', name='user_chat_pkey')
    )
    op.drop_index(op.f('ix_membership_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_friendship_id'), table_name='friendship')
    op.drop_table('friendship')
    # ### end Alembic commands ###
