"""added_not_null

Revision ID: 6acc4257a634
Revises: f15b3e795128
Create Date: 2023-03-01 01:12:42.646791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6acc4257a634'
down_revision = 'f15b3e795128'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block', 'blocker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('block', 'blocked_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('block_blocker_id_fkey', 'block', type_='foreignkey')
    op.drop_constraint('block_blocked_id_fkey', 'block', type_='foreignkey')
    op.create_foreign_key(None, 'block', 'user', ['blocked_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'block', 'user', ['blocker_id'], ['id'], ondelete='cascade')
    op.alter_column('chat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('friendship', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friendship', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friendship', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('friendship_receiver_id_fkey', 'friendship', type_='foreignkey')
    op.drop_constraint('friendship_sender_id_fkey', 'friendship', type_='foreignkey')
    op.create_foreign_key(None, 'friendship', 'user', ['receiver_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'friendship', 'user', ['sender_id'], ['id'], ondelete='cascade')
    op.alter_column('membership', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('membership', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('membership_user_id_fkey', 'membership', type_='foreignkey')
    op.drop_constraint('membership_chat_id_fkey', 'membership', type_='foreignkey')
    op.create_foreign_key(None, 'membership', 'chat', ['chat_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'membership', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('message_sender_id_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_chat_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_chat_id_fkey', 'message', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key('message_sender_id_fkey', 'message', 'user', ['sender_id'], ['id'])
    op.alter_column('message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('message', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'membership', type_='foreignkey')
    op.drop_constraint(None, 'membership', type_='foreignkey')
    op.create_foreign_key('membership_chat_id_fkey', 'membership', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key('membership_user_id_fkey', 'membership', 'user', ['user_id'], ['id'])
    op.alter_column('membership', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('membership', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'friendship', type_='foreignkey')
    op.drop_constraint(None, 'friendship', type_='foreignkey')
    op.create_foreign_key('friendship_sender_id_fkey', 'friendship', 'user', ['sender_id'], ['id'])
    op.create_foreign_key('friendship_receiver_id_fkey', 'friendship', 'user', ['receiver_id'], ['id'])
    op.alter_column('friendship', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('friendship', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('friendship', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'block', type_='foreignkey')
    op.drop_constraint(None, 'block', type_='foreignkey')
    op.create_foreign_key('block_blocked_id_fkey', 'block', 'user', ['blocked_id'], ['id'])
    op.create_foreign_key('block_blocker_id_fkey', 'block', 'user', ['blocker_id'], ['id'])
    op.alter_column('block', 'blocked_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('block', 'blocker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
