"""user password required

Revision ID: c5bdf2407549
Revises: dc28cf661924
Create Date: 2022-10-18 23:12:23.158635

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c5bdf2407549"
down_revision = "dc28cf661924"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_id", table_name="chat")
    op.drop_index("ix_friendship_id", table_name="friendship")
    op.drop_index("ix_membership_id", table_name="membership")
    op.drop_index("ix_message_id", table_name="message")
    op.alter_column(
        "user", "username", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "user",
        "password",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_index("ix_user_id", table_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_id", "user", ["id"], unique=False)
    op.alter_column(
        "user", "password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "user", "username", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.create_index("ix_message_id", "message", ["id"], unique=False)
    op.create_index("ix_membership_id", "membership", ["id"], unique=False)
    op.create_index("ix_friendship_id", "friendship", ["id"], unique=False)
    op.create_index("ix_chat_id", "chat", ["id"], unique=False)
    # ### end Alembic commands ###
