"""chat is_owner field

Revision ID: 2482bd8ee410
Revises: c5bdf2407549
Create Date: 2023-01-09 19:03:12.476031

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2482bd8ee410'
down_revision = 'c5bdf2407549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('is_owner', sa.Boolean(), nullable=True))
    op.execute('UPDATE membership SET is_owner = false')
    op.alter_column('membership', 'is_owner', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membership', 'is_owner')
    # ### end Alembic commands ###
